version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - backend

  mysql:
    build:
      context: .
      dockerfile: dockerfile.sql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: login_database
      MYSQL_USER: administrator
      MYSQL_PASSWORD: administrator
    ports:
      - "3307:3306"
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
