version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: dockerfile.sql
    ports:
      - "3307:3306"
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
